// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivqqesohskoxmkgnnnoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cXFlc29oc2tveG1rZ25ubm96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDI3MjYsImV4cCI6MjA2ODc3ODcyNn0.8t5JZ4_vFngo7Ssv_fVtNmesxgdK30nXi2xyj_mniWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});